### ISSUE TITLE
Likely typo in Rule4b.java

### ISSUE THREAD

**Issue by greglandrum** [SiMolecule/centres#1]
https://github.com/SiMolecule/centres/blob/33e09a3a40bd766008acc18fdd939209b529b82c/core/src/main/java/com/simolecule/centres/rules/Rule4b.java#L384

This line likely should be:
```
          int cmp = list1.get(i).compareTo(list2.get(i));
```

noticed while doing the RDKit "port" of this.

**Comment by johnmay** [comment]
Yes looks that way, been a while but IIRC Rule 4b is a bit of a mess and is where most of the corner-cases, complexities and revisions are.

Have fixed - thanks.
