### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by Kohulan** [SiMolecule/centres#10]
Hi @johnmay ,

If I need to reference this work, should I cite the GitHub repository directly or this paper?

https://chemrxiv.org/engage/chemrxiv/article-details/60c73e14337d6ca46ae26282

- Kohulan

**Comment by johnmay** [comment]
Both please

**Comment by johnmay** [comment]
But don't cite the preprint - there is one a JCIM

**Comment by johnmay** [comment]
https://pubs.acs.org/doi/10.1021/acs.jcim.8b00324

**Comment by Kohulan** [comment]
Great Thanks! 😃
