### ISSUE TITLE
Atropisomeric issue: result based on order of bonds from atom in BaseMol

### ISSUE THREAD

**Issue by iclkevin** [SiMolecule/centres#13]
I believe I have found an issue with the Atropisomeric class. I randomly receive a M or P in return, it is never consistent. I have  double checked that the foci and neighbors and config are all consistent. I can also verify the issue by adding a "Collections.shuffle()" of the bonds returned in the BaseMol.getBonds() function. If I enforce a certain order of the bonds in this function, I will receive a consistent result, but not always the correct one.

**Comment by johnmay** [comment]
Do you have an example molecule. The CDK tests use BiNAP and adding the following:

```
@Override
public Iterable<IBond> getBonds(IAtom atom)
{
  List<IBond> connectedBondsList = new ArrayList<>(base.getConnectedBondsList(atom));
  Collections.shuffle(connectedBondsList);
  return connectedBondsList;
}
```

Running TestAtropisomers 1000 times on M/P versions I do not see any wobble.

**Comment by iclkevin** [comment]
My apologies, this was a dumb mistake on my side. I spelled a variable wrong and was referencing the wrong atom copies. Thank you for double checking the Atropisomeric class.

**Comment by johnmay** [comment]
No worries, did have this issue before so thought it was possible.
