### ISSUE TITLE
more opportunistic stereo assignment for polymers

### ISSUE THREAD

**Issue by egonw** [SiMolecule/centres#6]
See https://github.com/cdk/depict/issues/48#issuecomment-1257567395 

The following example shows that the polymer version of the monomer could have stereochemistry, under reasonable assumptions. Actually, I think the missing R/S annotation on the left can actually be resolved without knowing the `*` (not?):

![image](https://user-images.githubusercontent.com/26721/192274370-33b8e07d-813c-40f6-bc87-766930ffca9d.png)

**Comment by johnmay** [comment]
Fixed in release 1.2 (and 1.2.1). Not sure if live on SiMolecule/cdkdepict yet though.
